<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <p>
        <br />
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ind" DataSourceID="SqlDataSource1">

            <Columns>
                <asp:BoundField DataField="ind" HeaderText="ind" InsertVisible="False" ReadOnly="True" SortExpression="ind" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="number" HeaderText="number" SortExpression="number" />
                <asp:BoundField DataField="adr" HeaderText="adr" SortExpression="adr" />
            </Columns>
        </asp:GridView>
        
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" DeleteCommand="DELETE FROM [Phones_Test] WHERE [ind] = @ind" InsertCommand="INSERT INTO [Phones_Test] ([name], [number], [adr]) VALUES (@name, @number, @adr)" SelectCommand="SELECT * FROM [Phones_Test]" UpdateCommand="UPDATE [Phones_Test] SET [name] = @name, [number] = @number, [adr] = @adr WHERE [ind] = @ind">
<DeleteParameters>
<asp:Parameter Name="ind" Type="Int32" />
</DeleteParameters>
<InsertParameters>
<asp:Parameter Name="name" Type="String" />
<asp:Parameter Name="number" Type="String" />
<asp:Parameter Name="adr" Type="String" />
</InsertParameters>
<UpdateParameters>
<asp:Parameter Name="name" Type="String" />
<asp:Parameter Name="number" Type="String" />
<asp:Parameter Name="adr" Type="String" />
<asp:Parameter Name="ind" Type="Int32" />
</UpdateParameters>
</asp:SqlDataSource>
    </p>
    <p>
        <asp:Button ID="Button1" runat="server" Text="Button" onclick="Button1_Click"/>
    </p>
</asp:Content>
